version: '3.4'

services:
  clubeventmanagementapi:
    image: ${DOCKER_REGISTRY-}clubeventmanagementapi
    build:
      context: .
      dockerfile: ClubEventManagementAPI/Dockerfile
    ports:
            - "5050:80"
            - "5051:443"
    environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=44311
            - DOTNET_VERSION=5.0.7
            - ASPNET_VERSION=5.0.7      
            - ASPNETCORE_Kestrel__Certificates__Default__Password=khoile
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
            - ./conf.d/https/:/https/
